### ISSUE TITLE
Incorrectly reporting SSLv3 support?

### ISSUE THREAD

**Issue by marklkelly** [pornin/TestSSLServer#3]
Hi,

I'm noticing that this tool has identified some servers as supporting SSL 3.0, when other tools (e.g ssllabs), run against the same server, report that SSL 3.0 isn't enabled. Is this a known issue?

This domain illustrates the point: d2nnjlsh3usk06.cloudfront.net. I get a "WARN[PV003]: Server supports SSL 3.0." message, however if I attempt to connect via openssl using sslv3, I can't e.g.

`openssl s_client -connect d2nnjlsh3usk06.cloudfront.net:443 -servername d2nnjlsh3usk06.cloudfront.net -ssl3`

Also, the SSL labs report indicates that SSLv3 is not supported: https://www.ssllabs.com/ssltest/analyze.html?d=d2nnjlsh3usk06.cloudfront.net&s=52.84.213.210&latest

**Comment by pornin** [comment]
On Thu, Aug 11, 2016 at 11:05:44AM -0700, marklkelly wrote:

> I'm noticing that this tool has identified some servers as supporting
> SSL 3.0, when other tools (e.g ssllabs), run against the same server,
> report that SSL 3.0 isn't enabled. Is this a known issue?

There is no such known issue. This might be an _unknown_ issue?

Normally, TestSSLServer reports that SSL 3.0 is supported when it
received a ServerHello that indicates usage of that exact protocol
version. Specifically, the cipher suite enumerator repeatedly attempts
connections with various client parameters, and considers only server
responses for which the protocol version used by the server matches the
"maximum version" sent by the client (see FullTest.cs, line 834).

To get down to it, try obtaining a network trace, with a tool like
Wireshark or Network Monitor, while TestSSLServer is running; and look
at the ServerHello sent by the server. If one of them says "protocol
version: 3.0" (in the ServerHello, not the record header), then the
server certainly claims to be able to use SSL 3.0.

```
--Thomas
```

**Comment by marklkelly** [comment]
I ran it through wireshark as per your suggestion, and did a comparison with OpenSSL - which I think has given me an answer (kind of!). 

TestSSLServer is sending TLS extensions (specifically server_name) with the SSL v3 client_hello, whereas OpenSSL doesn't do this. This means I see an error from OpenSSL but not from TestSSLServer when attempting a v3 connection.

The SSL 3.0 spec actually permits additional data - so I guess it would be up to the server to ignore that data for SSL 3.0 connections - which it doesn't appear to do.
